#!/bin/sh
#
# Pre-commit hooks

# Allows us to change directory in this script
unset GIT_DIR

cd frontend

# Validate CSS
CSS_SRC_PATTERN="\.scss"
git diff --cached --name-only | if grep "$CSS_SRC_PATTERN"
then
    npm run compileCss
fi
cssValidateResult=$?

# Validate JS
JS_SRC_PATTERN="\.js$"
git diff --cached --name-only | if grep "$JS_SRC_PATTERN"
then
    npm test
fi
jsValidateResult=$?

# Test JS CHANGE TO RIGHT PATTERN
git diff --cached --name-only | if grep "[^/]\+/\(app/assets/javascripts\|test/js/spec\).*$JS_SRC_PATTERN"
then
    npm test
fi
jsTestResult=$?


# Exit code 1 means don't commit and 0 means do commit
[ $cssValidateResult -ne 0 ] || [ $jsValidateResult -ne 0 ] || [ $jsTestResult -ne 0 ] && exit 1
exit 0
