#!/bin/bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
nvm install # uses .nvmrc, so everyone uses the same version of node, hopefully

set -o xtrace
set -o nounset
set -o errexit

# Installing yarn
YARN_VERSION="1.2.1"
YARN_LOCATION="tools/${YARN_VERSION}"

if [ ! -d "$YARN_LOCATION" ]; then
  mkdir -p ${YARN_LOCATION}
  cd ${YARN_LOCATION}/
  wget -qO- https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz | tar zvx
  cd ../..
fi

################################################################################
# Build the static asset files for the project
# Files will now be found in Public folder
################################################################################

${YARN_LOCATION}/yarn-v${YARN_VERSION}/bin/yarn cache clean
${YARN_LOCATION}/yarn-v${YARN_VERSION}/bin/yarn install

./node_modules/.bin/grunt "$@"
