#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

################################################################################
#
# Build the static asset files for the project - files will now be found in Public folder
#
################################################################################

JS_DIR=assets/javascripts
SCSS_DIR=assets/stylesheets

# Try newer ruby for newer sass
eval "$(rbenv init -)"
rbenv install -s 2.1.2
rbenv local 2.1.2

ruby --version

# Add bundler to the local ruby and rehash paths to pick it up
gem install bundler
rbenv rehash

export PATH=dev/gems/bin:$PATH
bundle install --binstubs dev/gems/bin --path dev/gems

npm cache clean
npm install

grunt "$@"
