#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit


################################################################################
#
# Build the static and executable jar packages for the $1 project.
#
################################################################################

./grunt-tc test compile
./sbt-tc clean scoverage:test play-artifact
