#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit



# Need node, npm, bower, karma-cli, sass installed globally

# make sure gems available in PATH
export PATH=dev/gems/bin:$PATH
bundle install --binstubs dev/gems/bin --path dev/gems

npm install

cd common/app/assets/javascripts

bower install

cd ../../../../

cd common/app/assets/stylesheets

bower install

cd ../../../../

grunt compile

grunt test

#grunt "$@"