#!/bin/sh
#
# Pre-commit hooks


# Validate CSS
CSS_SRC_PATTERN="\.scss"
git diff --cached --name-only | if grep "CSS_SRC_PATTERN"
then
    cd membership; grunt compile:css; cd ..
fi
cssValidateResult=$?

# Validate JS
JS_SRC_PATTERN="\.js$"
git diff --cached --name-only | if grep "$JS_SRC_PATTERN"
then
    cd membership; grunt jshint; cd ..;
fi
jsValidateResult=$?

# Test JS CHANGE TO RIGHT PATTERN
git diff --cached --name-only | if grep "[^/]\+/\(app/assets/javascripts\|test/js/spec\).*$JS_SRC_PATTERN"
then
    cd membership; grunt test:unit; cd ..;
fi
jsTestResult=$?


# Exit code 1 means don't commit and 0 means do commit
[ $cssValidateResult -ne 0 ] || [ $jsValidateResult -ne 0 ] || [ $jsTestResult -ne 0 ] && exit 1
exit 0
