name: Build membership-frontend

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    membership_frontend_build:
        if: >-
            (github.actor != 'dependabot[bot]') &&
              (github.repository_owner == 'guardian' ||
                github.event_name == 'push')

        # Required by actions-assume-aws-role
        permissions:
            id-token: write
            contents: read

        name: membership-frontend build
        runs-on: ubuntu-latest
        steps:
            - name: Env
              run: env

            - name: Set Time Zone to GMT # Setting the Timezone as the test cases except it to be to Europe/London(for the daylight saving changes #
              run: |
                sudo timedatectl set-timezone Europe/London

            - name: Checkout repo
              uses: actions/checkout@v3

        # (Respects .nvmrc)
            - name: Setup Node
              uses: guardian/actions-setup-node@v2.4.1
              with:
                  cache: "yarn"
                  cache-dependency-path: frontend/yarn.lock

            - name: Run Grunt and Install yarn
              run: |
                set -o xtrace
                set -o nounset
                set -o errexit
                export YARN_VERSION="1.12.3"
                export YARN_LOCATION="tools/${YARN_VERSION}"
                if [ ! -d "$YARN_LOCATION" ]; then
                mkdir -p ${YARN_LOCATION}
                cd ${YARN_LOCATION}/
                wget -qO- https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz | tar zvx
                cd ../..
                fi
              working-directory: frontend

            - name: Install Dependencies
              run: |
                  export YARN_VERSION="1.12.3"
                  export YARN_LOCATION="tools/${YARN_VERSION}"
                  ${YARN_LOCATION}/yarn-v${YARN_VERSION}/bin/yarn cache clean
                  ${YARN_LOCATION}/yarn-v${YARN_VERSION}/bin/yarn install
                  yarn "$@"
              working-directory: frontend

            - name: Build the static asset files for the project
              run: |
                  ./node_modules/.bin/grunt "$@" --force
              working-directory: frontend

            # Required by sbt riffRaffUpload
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
                  aws-region: eu-west-1

            - name: Setup Java 8
              uses: actions/setup-java@v3
              with:
                  java-version: "8"
                  distribution: "adopt"
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.ivy2/cache
                      ~/.sbt
                      ~/.coursier
                  key: sbt

        # ---- Test ---- #
            - name: Test - membership-frontend
              run: yarn run test
              working-directory: frontend

            - name: Build and upload to RiffRaff
              run: |
                  export LAST_TEAMCITY_BUILD=15000
                  sbt "project frontend" riffRaffUpload
