# This action is just a test
name: Snyk (test)

on: push

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-test
      SKIP_NODE: false
      EXCLUDE: frontend/build.sbt
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
